/**
 * Text Moderation Configuration
 *
 * Defines word sets and rules for content moderation of text descriptions.
 */

// UNICODE MAPPING
// Characters that look similar but are different Unicode points

export const HOMOGLYPHS: Record<string, string> = {
  // Cyrillic lookalikes
  а: "a",
  е: "e",
  і: "i",
  о: "o",
  р: "p",
  с: "c",
  у: "y",
  х: "x",
  ѕ: "s",
  ј: "j",
  һ: "h",
  ԁ: "d",
  ԝ: "w",
  ɡ: "g",
  ʙ: "b",
  ɴ: "n",
  ᴍ: "m",
  ᴛ: "t",
  ᴋ: "k",
  ɪ: "i",
  // Greek characters that look similar 
  α: "a",
  ε: "e",
  ι: "i",
  ο: "o",
  ρ: "p",
  τ: "t",
  υ: "u",
  ν: "v",
  // Special characters
  ℓ: "l",
  "№": "no",
  "℮": "e",
};

// LEETSPEAK REPLACEMENTS

export const LEETSPEAK: Record<string, string> = {
  "0": "o",
  "1": "i",
  "2": "z",
  "3": "e",
  "4": "a",
  "5": "s",
  "6": "g",
  "7": "t",
  "8": "b",
  "9": "g",
  "@": "a",
  $: "s",
  "!": "i",
  "|": "i",
  "+": "t",
};

// BLACKLIST ABSOLUTA
// Terms that ALWAYS result in block, no context needed

export const BLACKLIST_ABSOLUTE: string[] = [
  "cp",
  "pthc",
  "pedo",
  "pedofil",
  "pedofilo",
  "pedofilia",
  "pedophil",
  "pedophile",
  "pedophilia",
  "loli",
  "lolita",
  "lolicon",
  "shota",
  "shotacon",
  "jailbait",
  "preteen",
  "preteens",
  "cheesepizza",
  "cheese pizza",
  "pizzagate",
  "cub",
  "cubs", 
  "map pride",
  "nomap",
  "pro map",
  "pornografia infantil",
  "porno infantil",
  "abuso infantil",
  "abuso de menores",
  "child porn",
  "child abuse",
  "kiddie porn",
  "underage porn",
  "underage sex",
];

// WORD SETS FOR CONTEXTUAL DETECTION

/**
 * MINORS SET
 */
export const MINORS_SET: string[] = [
  "niño",
  "niños",
  "niña",
  "niñas",
  "niñx",
  "niñes",
  "menor",
  "menores",
  "infante",
  "infantes",
  "bebe",
  "beba",
  "bebes",
  "bebé",
  "bebés",
  "adolescente",
  "adolescentes",
  "joven",
  "jovenes",
  "jóvenes",
  "jovencito",
  "jovencita",
  "chico",
  "chica",
  "chicos",
  "chicas",
  "chiquito",
  "chiquita",
  "chiquitin",
  "chiquitina",
  "peque",
  "peques",
  "pequeño",
  "pequeña",
  "nene",
  "nena",
  "nenes",
  "nenas",
  "criatura",
  "criaturas",
  "crio",
  "cria",
  "crios",
  "chamaco",
  "chamaca",
  "chamacos",
  "escolar",
  "escolares",
  "escuelita",
  "alumno",
  "alumna",
  "alumnos",
  "alumnas",
  "estudiante",
  "estudiantes",
  "puberto",
  "puberta",
  "pubertos",
  "morro",
  "morra",
  "morros",
  "morras",
  "morrito",
  "morrita",
  "chavito",
  "chavita",
  "chavitos",
  "chavitas",
  "patojo",
  "patoja",
  "patojos",
  "cipote",
  "cipotes",
  "cipota",
  "guri",
  "gurí",
  "guris",
  "pibe",
  "piba",
  "pibes",
  "pibas",
  "pibito",
  "pibita",
  "pendejo",
  "pendeja", 
  "chavo",
  "chava",
  "chavos",
  "chavas",
  "wey menor",
  "wea menor",
  "child",
  "children",
  "kid",
  "kids",
  "kiddo",
  "kiddos",
  "teen",
  "teens",
  "teenager",
  "teenagers",
  "boy",
  "boys",
  "girl",
  "girls",
  "young",
  "younger",
  "youngest",
  "minor",
  "minors",
  "underage",
  "toddler",
  "toddlers",
  "infant",
  "infants",
  "juvenile",
  "juveniles",
  "youth",
  "youths",
  "schoolgirl",
  "schoolboy",
  "schoolkid",
  "preteen",
  "preteens",
  "tween",
  "tweens",
  "añitos",
  "añito",
  "years old",
  "yrs old",
  "yr old",
  "años",
  "año",
];

/**
 * Age numbers that are dangerous when combined with other sets
 */
export const CONCERNING_AGES: string[] = [
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "ocho",
  "nueve",
  "diez",
  "once",
  "doce",
  "trece",
  "catorce",
  "quince",
  "dieciseis",
  "diecisiete",
  "eight",
  "nine",
  "ten",
  "eleven",
  "twelve",
  "thirteen",
  "fourteen",
  "fifteen",
  "sixteen",
  "seventeen",
  "viii",
  "ix",
  "x",
  "xi",
  "xii",
  "xiii",
  "xiv",
  "xv",
  "xvi",
  "xvii",
];

/**
 * SEXUAL SET
 * Words indicating sexual content
 */
export const SEXUAL_SET: string[] = [
  "sexo",
  "sexual",
  "sexuales",
  "sexualidad",
  "xxx",
  "nsfw",
  "+18",
  "18+",
  "mayores de 18",
  "porn",
  "porno",
  "pornografia",
  "pornográfico",
  "erotico",
  "erótico",
  "erotica",
  "erótica",
  "hot",
  "caliente",
  "calientes",
  "cachondo",
  "cachonda",
  "desnudo",
  "desnuda",
  "desnudos",
  "desnudas",
  "nude",
  "nudes",
  "nudismo",
  "intimo",
  "íntimo",
  "intima",
  "íntima",
  "intimidades",
  "sensual",
  "sensuales",
  "excitante",
  "excitado",
  "excitada",
  "morbo",
  "morboso",
  "morbosa",
  "pervertido",
  "pervertida",
  "perversion",
  "fetiche",
  "fetiches",
  "fetish",
  "kinky",
  "kink",
  "sucio",
  "sucia",
  "sucios",
  "sucias",
  "cochinadas",
  "obsceno",
  "obscena",
  "lujuria",
  "lujurioso",
  "pecaminoso",
  "pecaminosa",
  "sex",
  "sexy",
  "sexting",
  "porn",
  "porno",
  "pornographic",
  "erotic",
  "erotica",
  "nude",
  "nudes",
  "nudity",
  "naked",
  "intimate",
  "intimacy",
  "horny",
  "aroused",
  "arousing",
  "dirty",
  "filthy",
  "naughty",
  "lewd",
  "lewds",
  "obscene",
  "explicit",
  "adult content",
  "adult only",
  "xxx",
  "x rated",
  "xrated",
];

/**
 * MEDIA_EXCHANGE SET
 * Words indicating exchange or possession of dangerous content
 */
export const MEDIA_EXCHANGE_SET: string[] = [
  "foto",
  "fotos",
  "fotito",
  "fotitos",
  "fotografia",
  "fotografias",
  "imagen",
  "imágenes",
  "imagenes",
  "img",
  "imgs",
  "video",
  "videos",
  "vídeo",
  "vídeos",
  "vid",
  "vids",
  "contenido",
  "contenidos",
  "cont",
  "material",
  "materiales",
  "archivo",
  "archivos",
  "pack",
  "packs",
  "packete",
  "coleccion",
  "colección",
  "colecciones",
  "galeria",
  "galería",
  "galerias",
  "album",
  "álbum",
  "albumes",
  "grabacion",
  "grabación",
  "grabaciones",
  "clip",
  "clips",
  "selfie",
  "selfies",
  "pic",
  "pics",
  "photo",
  "photos",
  "photograph",
  "photographs",
  "image",
  "images",
  "img",
  "imgs",
  "video",
  "videos",
  "vid",
  "vids",
  "content",
  "contents",
  "material",
  "materials",
  "file",
  "files",
  "pack",
  "packs",
  "package",
  "collection",
  "collections",
  "gallery",
  "galleries",
  "album",
  "albums",
  "recording",
  "recordings",
  "clip",
  "clips",
  "selfie",
  "selfies",
  "pic",
  "pics",
  "picture",
  "pictures",
  "media",
];

/**
 * INTENT SET
 * Words indicating intent 
 */
export const INTENT_SET: string[] = [
  "vendo",
  "vende",
  "vender",
  "venta",
  "ventas",
  "compro",
  "compra",
  "comprar",
  "compras",
  "pago",
  "paga",
  "pagar",
  "pagos",
  "precio",
  "precios",
  "costo",
  "costos",
  "negocio",
  "negociable",
  "oferta",
  "ofertas",
  "gratis",
  "gratuito",
  "gratuita",
  "free",
  "intercambio",
  "intercambiar",
  "intercambiamos",
  "cambio",
  "cambiar",
  "cambiamos",
  "trade",
  "tradeo",
  "tradear",
  "swap",
  "swapeo",
  "trueque",
  "busco",
  "busca",
  "buscar",
  "buscamos",
  "buscando",
  "quiero",
  "quiere",
  "quieren",
  "queremos",
  "necesito",
  "necesita",
  "necesitamos",
  "ofrezco",
  "ofrece",
  "ofrecemos",
  "ofreciendo",
  "tengo",
  "tiene",
  "tenemos",
  "teniendo",
  "consigo",
  "consigue",
  "conseguir",
  "doy",
  "da",
  "dar",
  "damos",
  "proporciono",
  "proporciona",
  "comparto",
  "compartir",
  "compartimos",
  "disponible",
  "disponibles",
  "hay",
  "existe",
  "existen",
  "manda",
  "mando",
  "mandar",
  "mandame",
  "envia",
  "envio",
  "enviar",
  "enviame",
  "envíame",
  "paso",
  "pasa",
  "pasar",
  "pasame",
  "pásame",
  "sell",
  "selling",
  "sale",
  "buy",
  "buying",
  "pay",
  "paying",
  "payment",
  "price",
  "pricing",
  "cost",
  "deal",
  "deals",
  "offer",
  "offering",
  "free",

  "exchange",
  "exchanging",
  "trade",
  "trading",
  "swap",
  "swapping",

  "looking for",
  "seeking",
  "searching",
  "search",
  "want",
  "wanting",
  "wanted",
  "need",
  "needing",
  "needed",
  "have",
  "having",
  "got",
  "share",
  "sharing",
  "send",
  "sending",
  "give",
  "giving",
  "get",
  "getting",

  "available",
  "dm me",
  "dm for",
  "hmu",
  "hit me up",
];

/**
 * CONTACT SET
 * Words indicating attempt to move to private conversation
 */
export const CONTACT_SET: string[] = [
  "telegram",
  "tg",
  "t.me",
  "whatsapp",
  "wa",
  "wpp",
  "whats",
  "wsp",
  "discord",
  "dc",
  "snapchat",
  "snap",
  "sc",
  "kik",
  "signal",
  "wickr",
  "instagram",
  "insta",
  "ig",
  "twitter",
  "x.com",
  "tiktok",
  "tt",
  "facebook",
  "fb",
  "messenger",
  "skype",
  "wechat",
  "line",
  "dm",
  "md",
  "mensaje directo",
  "mensajes directos",
  "privado",
  "pv",
  "priv",
  "inbox",
  "ib",
  "escribeme",
  "escríbeme",
  "escribanme",
  "contacto",
  "contactame",
  "contáctame",
  "numero",
  "número",
  "cel",
  "celular",
  "chat",
  "chatear",
  "chatea",
  "hablame",
  "háblame",
  "hablemos",
  "agregame",
  "agrégame",
  "agregar",
  "añademe",
  "añádeme",
  "dm",
  "pm",
  "direct message",
  "private",
  "privately",
  "inbox",
  "message me",
  "msg me",
  "text me",
  "contact",
  "contact me",
  "number",
  "phone",
  "chat",
  "chat with",
  "add me",
  "follow me",
  "hit me up",
  "hmu",
  "slide into",
  "slides into",
];

/**
 * IMPLICIT SUSPICIOUS PATTERNS
 * Phrases that are suspicious
 */
export const IMPLICIT_SUSPICIOUS: string[] = [
  "lo que buscas",
  "lo que todos buscan",
  "sabes de que",
  "sabes de qué",
  "ya sabes",
  "lo prohibido",
  "cosas prohibidas",
  "material especial",
  "contenido especial",
  "exclusivo",
  "exclusivos",
  "secreto",
  "secretos",
  "ilegal",
  "ilegales",
  "lo bueno",
  "las buenas",
  "sin censura",
  "privado real",
  "solo para selectos",
  "grupo vip",
  "acceso especial",
  "no apto",
  "what you want",
  "what everyone wants",
  "you know what",
  "if you know",
  "forbidden",
  "prohibited",
  "special material",
  "special content",
  "exclusive",
  "exclusives",
  "secret",
  "secrets",
  "illegal",
  "the good stuff",
  "uncensored",
  "real private",
  "select only",
  "selected only",
  "vip group",
  "vip access",
  "special access",
  "not suitable",
];

/**
 * GROOMING ROLE INVERSION PATTERNS
 * Phrases that indicate potential grooming attempts where the predator tries to invert roles and present themselves as a minor or peer to gain trust. These are often used in combination with other sets to indicate intent.
 */
export const ROLE_INVERSION_PATTERNS: string[] = [
  "mi hija busca",
  "mi hijo busca",
  "mi sobrina",
  "mi sobrino",
  "mi prima menor",
  "mi primo menor",
  "mi hermana menor",
  "mi hermano menor",
  "tengo una amiga de",
  "tengo un amigo de",
  "conozco una chica",
  "conozco un chico",
  "presenta a mi",
  "te presento a mi",

  "my daughter wants",
  "my son wants",
  "my niece",
  "my nephew",
  "my younger cousin",
  "my little cousin",
  "my younger sister",
  "my younger brother",
  "my little sister",
  "my little brother",
  "i have a friend who",
  "i know a girl",
  "i know a boy",
  "introducing my",
  "meet my",
];

/**
 * SUSPICIOUS EMOJI COMBINATIONS
 * Emojis that can indicate coded communication
 */
export const SUSPICIOUS_EMOJIS: string[] = [
  "🍕",
  "🧀",
  "🍬",
  "🍭",
  "🍫",
  "👶",
  "👧",
  "👦",
  "🧒",
  "👨‍👧",
  "👨‍👦",
  "👩‍👧",
  "👩‍👦",
  "🔞",
  "💋",
  "🍑",
  "🍆",
  "💦",
  "😈",
  "🥵",
  "🤫",
  "🤐",
  "👀",
];

// SCORING CONFIGURATION

export interface ScoringConfig {
  /** Minimum score to trigger a BLOCK */
  blockThreshold: number;
  /** Minimum score to trigger a REVIEW */
  reviewThreshold: number;
}

export const SCORING_CONFIG: ScoringConfig = {
  blockThreshold: 10,
  reviewThreshold: 6,
};

// COMBINATION SCORES

export interface CombinationScore {
  sets: string[];
  score: number;
  action: "BLOCK" | "REVIEW" | "FLAG";
  reason: string;
}

/**
 * Scores for different set combinations
 */
export const COMBINATION_SCORES: CombinationScore[] = [
  // Immediate block
  {
    sets: ["SEXUAL", "MINORS"],
    score: 15,
    action: "BLOCK",
    reason: "SEXUAL_MINORS_COMBINATION",
  },
  {
    sets: ["INTENT", "MINORS"],
    score: 12,
    action: "BLOCK",
    reason: "INTENT_MINORS_COMBINATION",
  },
  {
    sets: ["MEDIA", "MINORS"],
    score: 15,
    action: "BLOCK",
    reason: "MEDIA_MINORS_COMBINATION",
  },
  {
    sets: ["CONTACT", "MINORS"],
    score: 12,
    action: "BLOCK",
    reason: "CONTACT_MINORS_COMBINATION",
  },
  {
    sets: ["INTENT", "SEXUAL"],
    score: 10,
    action: "BLOCK",
    reason: "INTENT_SEXUAL_COMBINATION",
  },
  {
    sets: ["SEXUAL", "CONTACT"],
    score: 10,
    action: "BLOCK",
    reason: "SEXUAL_CONTACT_COMBINATION",
  },
  {
    sets: ["INTENT", "MEDIA", "SEXUAL"],
    score: 12,
    action: "BLOCK",
    reason: "INTENT_MEDIA_SEXUAL_COMBINATION",
  },
  {
    sets: ["INTENT", "MEDIA", "MINORS"],
    score: 15,
    action: "BLOCK",
    reason: "INTENT_MEDIA_MINORS_COMBINATION",
  },

  // HIGH RISK - Should review
  {
    sets: ["MEDIA", "CONTACT"],
    score: 7,
    action: "REVIEW",
    reason: "MEDIA_CONTACT_COMBINATION",
  },
  {
    sets: ["INTENT", "CONTACT"],
    score: 6,
    action: "REVIEW",
    reason: "INTENT_CONTACT_COMBINATION",
  },
  {
    sets: ["MEDIA", "SEXUAL"],
    score: 8,
    action: "REVIEW",
    reason: "MEDIA_SEXUAL_COMBINATION",
  },

  // AGE-SPECIFIC COMBINATIONS
  {
    sets: ["AGE", "SEXUAL"],
    score: 15,
    action: "BLOCK",
    reason: "AGE_SEXUAL_COMBINATION",
  },
  {
    sets: ["AGE", "MEDIA"],
    score: 12,
    action: "BLOCK",
    reason: "AGE_MEDIA_COMBINATION",
  },
  {
    sets: ["AGE", "CONTACT"],
    score: 10,
    action: "BLOCK",
    reason: "AGE_CONTACT_COMBINATION",
  },
  {
    sets: ["AGE", "INTENT"],
    score: 10,
    action: "BLOCK",
    reason: "AGE_INTENT_COMBINATION",
  },
];

// FALSE POSITIVE PROTECTION (WHITELIST CONTEXTS)

/**
 * Phrases that indicate legitimate context
 */
export const LEGITIMATE_CONTEXTS: string[] = [
  "clases para",
  "clases de",
  "cursos para",
  "cursos de",
  "educacion",
  "educación",
  "educativo",
  "educativa",
  "escuela",
  "colegio",
  "instituto",
  "profesor",
  "profesora",
  "maestro",
  "maestra",
  "tutor",
  "tutora",
  "tutoria",
  "tutoría",
  "niñera",
  "niñero",
  "cuidador",
  "cuidadora",
  "guarderia",
  "guardería",
  "apoyo escolar",
  "ayuda escolar",
  "padres",
  "madres",
  "familia",
  "familias",
  "pediatra",
  "pediatría",
  "psicólogo infantil",
  "psicologo infantil",

  "ropa para",
  "ropa de",
  "juguetes para",
  "juguetes de",
  "libros para",
  "libros de",
  "articulos para",
  "artículos para",

  "classes for",
  "courses for",
  "lessons for",
  "education",
  "educational",
  "school",
  "college",
  "teacher",
  "tutor",
  "tutoring",
  "babysitter",
  "nanny",
  "caregiver",
  "daycare",
  "childcare",
  "homework help",
  "study help",
  "parents",
  "family",
  "families",
  "pediatric",
  "pediatrician",
  "child psychologist",

  "clothes for",
  "clothing for",
  "toys for",
  "books for",
  "products for",
  "items for",
];

// AGE PATTERNS (REGEX)

export const AGE_PATTERNS: RegExp[] = [
  // Spanish 
  /\b(\d{1,2})\s*(años?|añitos?)\b/gi,
  /\b(menor|menores)\s+de\s+(\d{1,2})\b/gi,
  /\bde\s+(\d{1,2})\s+(años?|añitos?)\b/gi,
  /\b(\d{1,2})\s*-\s*(\d{1,2})\s*(años?)?\b/gi, 
  /\bsub\s*(\d{1,2})\b/gi, 
  /\b\+?\s*(\d{1,2})\s*\+?\b/gi, 

  // English 
  /\b(\d{1,2})\s*(years?\s*old|y\.?o\.?|yrs?\s*old)\b/gi,
  /\bunder\s*(\d{1,2})\b/gi,
  /\b(\d{1,2})\s*to\s*(\d{1,2})\s*(years?\s*old|y\.?o\.?)?\b/gi,
];

/**
 * Ages that are concerning (8-17)
 */
export const CONCERNING_AGE_RANGE = { min: 8, max: 17 };

// RESPONSE TYPES

export type ModerationAction = "ALLOW" | "REVIEW" | "BLOCK";

export interface TextModerationResult {
  action: ModerationAction;
  score: number;
  reason?: string;
  flags: ModerationFlag[];
  normalizedText: string;
  processingTimeMs: number;
}

export interface ModerationFlag {
  type: string;
  matched: string[];
  window?: string;
  score: number;
}

// USER-FACING MESSAGES

export const USER_MESSAGES: Record<string, string> = {
  BLACKLIST_HIT: "Your description contains prohibited content.",
  SEXUAL_MINORS_COMBINATION:
    "Your description was flagged for inappropriate content.",
  INTENT_MINORS_COMBINATION:
    "Your description was flagged for inappropriate content.",
  MEDIA_MINORS_COMBINATION:
    "Your description was flagged for inappropriate content.",
  CONTACT_MINORS_COMBINATION:
    "Your description was flagged for inappropriate content.",
  INTENT_SEXUAL_COMBINATION:
    "Your description contains adult content which is not allowed in public boards.",
  SEXUAL_CONTACT_COMBINATION:
    "Your description contains adult content which is not allowed in public boards.",
  INTENT_MEDIA_SEXUAL_COMBINATION:
    "Your description contains adult content which is not allowed in public boards.",
  INTENT_MEDIA_MINORS_COMBINATION:
    "Your description was flagged for inappropriate content.",
  AGE_SEXUAL_COMBINATION:
    "Your description was flagged for inappropriate content.",
  AGE_MEDIA_COMBINATION:
    "Your description was flagged for inappropriate content.",
  AGE_CONTACT_COMBINATION:
    "Your description was flagged for inappropriate content.",
  AGE_INTENT_COMBINATION:
    "Your description was flagged for inappropriate content.",
  IMPLICIT_SUSPICIOUS: "Your description contains suspicious language.",
  ROLE_INVERSION: "Your description was flagged for inappropriate content.",
  SUSPICIOUS_EMOJI: "Your description contains suspicious content.",
  HIGH_RISK_SCORE: "Your description was flagged for review.",
  DEFAULT: "Your description could not be approved.",
};
