export * from "./polygon";
export * from "./triangle";
export * from "./square";
export * from "./pentagon";
export * from "./hexagon";
export * from "./octagon";
export * from "./decagon";
export * from "./dodecagon";
export * from "./circle";
